/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/playmobil.gltf
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/playmobil.gltf");
  return (
    <group {...props} dispose={null} scale={2} position={[0, -2, 0]}>
      <mesh
        geometry={nodes.Mesh0.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        geometry={nodes.Mesh0_1.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        geometry={nodes.Mesh0_2.geometry}
        material={materials["Material.004"]}
      />
      <mesh
        geometry={nodes.Mesh0_3.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.Mesh0_4.geometry}
        material={materials["Material.008"]}
      />
      <mesh
        geometry={nodes.Mesh0_5.geometry}
        material={materials["Material.006"]}
      />
      <mesh
        geometry={nodes.Mesh0_6.geometry}
        material={materials["Material.007"]}
      />
    </group>
  );
}

useGLTF.preload("/models/playmobil.gltf");
